packages:
  - playground
  - packages/*
  - test
  - docs
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.5
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.24
  vite-plus: 0.2.5
overrides:
  vite: "catalog:"
  vitest: "catalog:"
  "@spark-ui/docs>vite": "npm:vite@5.4.21"
  "@spark-ui/docs>@unocss/vite>vite": "npm:vite@5.4.21"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
