import Vue from "@vitejs/plugin-vue";
import { defineConfig } from "vite-plus";
import { resolvePath } from "./config/utils/resolvePath";

export default defineConfig({
  plugins: [Vue()],
  test: {
    clearMocks: true,
    exclude: [
      "**/node_modules/**",
      "**/dist/**",
      // Stale agent git worktrees hold duplicated specs that hang the run
      "**/.claude/worktrees/**",
    ],
  },
  resolve: {
    alias: {
      "@spark-ui/ui": resolvePath("./packages/ui"),
      "@spark-ui/cli": resolvePath("./packages/cli"),
    },
  },
  staged: {
    "*.{js,ts,tsx,vue,md}": "vp check --fix",
  },
  fmt: {},
  lint: {
    plugins: ["oxc", "typescript", "unicorn", "react", "node", "jsdoc", "import"],
    jsPlugins: [
      {
        name: "vite-plus",
        specifier: "vite-plus/oxlint-plugin",
      },
    ],
    categories: {
      correctness: "warn",
    },
    options: {
      typeAware: true,
      typeCheck: true,
    },
    env: {
      builtin: true,
      commonjs: true,
      es2024: true,
    },
    globals: {
      AbortController: "readonly",
      AbortSignal: "readonly",
      AbsoluteOrientationSensor: "readonly",
      AbstractRange: "readonly",
      Accelerometer: "readonly",
      addEventListener: "readonly",
      ai: "readonly",
      AI: "readonly",
      AITextSession: "readonly",
      alert: "readonly",
      AnalyserNode: "readonly",
      Animation: "readonly",
      AnimationEffect: "readonly",
      AnimationEvent: "readonly",
      AnimationPlaybackEvent: "readonly",
      AnimationTimeline: "readonly",
      atob: "readonly",
      Attr: "readonly",
      Audio: "readonly",
      AudioBuffer: "readonly",
      AudioBufferSourceNode: "readonly",
      AudioContext: "readonly",
      AudioData: "readonly",
      AudioDecoder: "readonly",
      AudioDestinationNode: "readonly",
      AudioEncoder: "readonly",
      AudioListener: "readonly",
      AudioNode: "readonly",
      AudioParam: "readonly",
      AudioParamMap: "readonly",
      AudioProcessingEvent: "readonly",
      AudioScheduledSourceNode: "readonly",
      AudioSinkInfo: "readonly",
      AudioWorklet: "readonly",
      AudioWorkletGlobalScope: "readonly",
      AudioWorkletNode: "readonly",
      AudioWorkletProcessor: "readonly",
      AuthenticatorAssertionResponse: "readonly",
      AuthenticatorAttestationResponse: "readonly",
      AuthenticatorResponse: "readonly",
      BackgroundFetchManager: "readonly",
      BackgroundFetchRecord: "readonly",
      BackgroundFetchRegistration: "readonly",
      BarcodeDetector: "readonly",
      BarProp: "readonly",
      BaseAudioContext: "readonly",
      BatteryManager: "readonly",
      BeforeUnloadEvent: "readonly",
      BiquadFilterNode: "readonly",
      Blob: "readonly",
      BlobEvent: "readonly",
      Bluetooth: "readonly",
      BluetoothCharacteristicProperties: "readonly",
      BluetoothDevice: "readonly",
      BluetoothRemoteGATTCharacteristic: "readonly",
      BluetoothRemoteGATTDescriptor: "readonly",
      BluetoothRemoteGATTServer: "readonly",
      BluetoothRemoteGATTService: "readonly",
      BluetoothUUID: "readonly",
      blur: "readonly",
      BroadcastChannel: "readonly",
      BrowserCaptureMediaStreamTrack: "readonly",
      btoa: "readonly",
      ByteLengthQueuingStrategy: "readonly",
      Cache: "readonly",
      caches: "readonly",
      CacheStorage: "readonly",
      cancelAnimationFrame: "readonly",
      cancelIdleCallback: "readonly",
      CanvasCaptureMediaStream: "readonly",
      CanvasCaptureMediaStreamTrack: "readonly",
      CanvasGradient: "readonly",
      CanvasPattern: "readonly",
      CanvasRenderingContext2D: "readonly",
      CaptureController: "readonly",
      CaretPosition: "readonly",
      CDATASection: "readonly",
      ChannelMergerNode: "readonly",
      ChannelSplitterNode: "readonly",
      ChapterInformation: "readonly",
      CharacterBoundsUpdateEvent: "readonly",
      CharacterData: "readonly",
      clearInterval: "readonly",
      clearTimeout: "readonly",
      clientInformation: "readonly",
      Clipboard: "readonly",
      ClipboardEvent: "readonly",
      ClipboardItem: "readonly",
      close: "readonly",
      closed: "readonly",
      CloseEvent: "readonly",
      CloseWatcher: "readonly",
      Comment: "readonly",
      CompositionEvent: "readonly",
      CompressionStream: "readonly",
      confirm: "readonly",
      console: "readonly",
      ConstantSourceNode: "readonly",
      ContentVisibilityAutoStateChangeEvent: "readonly",
      ConvolverNode: "readonly",
      CookieChangeEvent: "readonly",
      CookieDeprecationLabel: "readonly",
      cookieStore: "readonly",
      CookieStore: "readonly",
      CookieStoreManager: "readonly",
      CountQueuingStrategy: "readonly",
      createImageBitmap: "readonly",
      Credential: "readonly",
      credentialless: "readonly",
      CredentialsContainer: "readonly",
      CropTarget: "readonly",
      crossOriginIsolated: "readonly",
      crypto: "readonly",
      Crypto: "readonly",
      CryptoKey: "readonly",
      CSS: "readonly",
      CSSAnimation: "readonly",
      CSSConditionRule: "readonly",
      CSSContainerRule: "readonly",
      CSSCounterStyleRule: "readonly",
      CSSFontFaceRule: "readonly",
      CSSFontFeatureValuesRule: "readonly",
      CSSFontPaletteValuesRule: "readonly",
      CSSGroupingRule: "readonly",
      CSSImageValue: "readonly",
      CSSImportRule: "readonly",
      CSSKeyframeRule: "readonly",
      CSSKeyframesRule: "readonly",
      CSSKeywordValue: "readonly",
      CSSLayerBlockRule: "readonly",
      CSSLayerStatementRule: "readonly",
      CSSMarginRule: "readonly",
      CSSMathClamp: "readonly",
      CSSMathInvert: "readonly",
      CSSMathMax: "readonly",
      CSSMathMin: "readonly",
      CSSMathNegate: "readonly",
      CSSMathProduct: "readonly",
      CSSMathSum: "readonly",
      CSSMathValue: "readonly",
      CSSMatrixComponent: "readonly",
      CSSMediaRule: "readonly",
      CSSNamespaceRule: "readonly",
      CSSNestedDeclarations: "readonly",
      CSSNumericArray: "readonly",
      CSSNumericValue: "readonly",
      CSSPageDescriptors: "readonly",
      CSSPageRule: "readonly",
      CSSPerspective: "readonly",
      CSSPositionTryDescriptors: "readonly",
      CSSPositionTryRule: "readonly",
      CSSPositionValue: "readonly",
      CSSPropertyRule: "readonly",
      CSSRotate: "readonly",
      CSSRule: "readonly",
      CSSRuleList: "readonly",
      CSSScale: "readonly",
      CSSScopeRule: "readonly",
      CSSSkew: "readonly",
      CSSSkewX: "readonly",
      CSSSkewY: "readonly",
      CSSStartingStyleRule: "readonly",
      CSSStyleDeclaration: "readonly",
      CSSStyleRule: "readonly",
      CSSStyleSheet: "readonly",
      CSSStyleValue: "readonly",
      CSSSupportsRule: "readonly",
      CSSTransformComponent: "readonly",
      CSSTransformValue: "readonly",
      CSSTransition: "readonly",
      CSSTranslate: "readonly",
      CSSUnitValue: "readonly",
      CSSUnparsedValue: "readonly",
      CSSVariableReferenceValue: "readonly",
      CSSViewTransitionRule: "readonly",
      currentFrame: "readonly",
      currentTime: "readonly",
      CustomElementRegistry: "readonly",
      customElements: "readonly",
      CustomEvent: "readonly",
      CustomStateSet: "readonly",
      DataTransfer: "readonly",
      DataTransferItem: "readonly",
      DataTransferItemList: "readonly",
      DecompressionStream: "readonly",
      DelayNode: "readonly",
      DelegatedInkTrailPresenter: "readonly",
      DeviceMotionEvent: "readonly",
      DeviceMotionEventAcceleration: "readonly",
      DeviceMotionEventRotationRate: "readonly",
      DeviceOrientationEvent: "readonly",
      devicePixelRatio: "readonly",
      dispatchEvent: "readonly",
      document: "readonly",
      Document: "readonly",
      DocumentFragment: "readonly",
      documentPictureInPicture: "readonly",
      DocumentPictureInPicture: "readonly",
      DocumentPictureInPictureEvent: "readonly",
      DocumentTimeline: "readonly",
      DocumentType: "readonly",
      DOMError: "readonly",
      DOMException: "readonly",
      DOMImplementation: "readonly",
      DOMMatrix: "readonly",
      DOMMatrixReadOnly: "readonly",
      DOMParser: "readonly",
      DOMPoint: "readonly",
      DOMPointReadOnly: "readonly",
      DOMQuad: "readonly",
      DOMRect: "readonly",
      DOMRectList: "readonly",
      DOMRectReadOnly: "readonly",
      DOMStringList: "readonly",
      DOMStringMap: "readonly",
      DOMTokenList: "readonly",
      DragEvent: "readonly",
      DynamicsCompressorNode: "readonly",
      EditContext: "readonly",
      Element: "readonly",
      ElementInternals: "readonly",
      EncodedAudioChunk: "readonly",
      EncodedVideoChunk: "readonly",
      ErrorEvent: "readonly",
      event: "readonly",
      Event: "readonly",
      EventCounts: "readonly",
      EventSource: "readonly",
      EventTarget: "readonly",
      external: "readonly",
      External: "readonly",
      EyeDropper: "readonly",
      FeaturePolicy: "readonly",
      FederatedCredential: "readonly",
      fence: "readonly",
      Fence: "readonly",
      FencedFrameConfig: "readonly",
      fetch: "readonly",
      fetchLater: "readonly",
      FetchLaterResult: "readonly",
      File: "readonly",
      FileList: "readonly",
      FileReader: "readonly",
      FileSystem: "readonly",
      FileSystemDirectoryEntry: "readonly",
      FileSystemDirectoryHandle: "readonly",
      FileSystemDirectoryReader: "readonly",
      FileSystemEntry: "readonly",
      FileSystemFileEntry: "readonly",
      FileSystemFileHandle: "readonly",
      FileSystemHandle: "readonly",
      FileSystemWritableFileStream: "readonly",
      find: "readonly",
      focus: "readonly",
      FocusEvent: "readonly",
      FontData: "readonly",
      FontFace: "readonly",
      FontFaceSet: "readonly",
      FontFaceSetLoadEvent: "readonly",
      FormData: "readonly",
      FormDataEvent: "readonly",
      FragmentDirective: "readonly",
      frameElement: "readonly",
      frames: "readonly",
      GainNode: "readonly",
      Gamepad: "readonly",
      GamepadAxisMoveEvent: "readonly",
      GamepadButton: "readonly",
      GamepadButtonEvent: "readonly",
      GamepadEvent: "readonly",
      GamepadHapticActuator: "readonly",
      GamepadPose: "readonly",
      Geolocation: "readonly",
      GeolocationCoordinates: "readonly",
      GeolocationPosition: "readonly",
      GeolocationPositionError: "readonly",
      getComputedStyle: "readonly",
      getScreenDetails: "readonly",
      getSelection: "readonly",
      GPU: "readonly",
      GPUAdapter: "readonly",
      GPUAdapterInfo: "readonly",
      GPUBindGroup: "readonly",
      GPUBindGroupLayout: "readonly",
      GPUBuffer: "readonly",
      GPUBufferUsage: "readonly",
      GPUCanvasContext: "readonly",
      GPUColorWrite: "readonly",
      GPUCommandBuffer: "readonly",
      GPUCommandEncoder: "readonly",
      GPUCompilationInfo: "readonly",
      GPUCompilationMessage: "readonly",
      GPUComputePassEncoder: "readonly",
      GPUComputePipeline: "readonly",
      GPUDevice: "readonly",
      GPUDeviceLostInfo: "readonly",
      GPUError: "readonly",
      GPUExternalTexture: "readonly",
      GPUInternalError: "readonly",
      GPUMapMode: "readonly",
      GPUOutOfMemoryError: "readonly",
      GPUPipelineError: "readonly",
      GPUPipelineLayout: "readonly",
      GPUQuerySet: "readonly",
      GPUQueue: "readonly",
      GPURenderBundle: "readonly",
      GPURenderBundleEncoder: "readonly",
      GPURenderPassEncoder: "readonly",
      GPURenderPipeline: "readonly",
      GPUSampler: "readonly",
      GPUShaderModule: "readonly",
      GPUShaderStage: "readonly",
      GPUSupportedFeatures: "readonly",
      GPUSupportedLimits: "readonly",
      GPUTexture: "readonly",
      GPUTextureUsage: "readonly",
      GPUTextureView: "readonly",
      GPUUncapturedErrorEvent: "readonly",
      GPUValidationError: "readonly",
      GravitySensor: "readonly",
      Gyroscope: "readonly",
      HashChangeEvent: "readonly",
      Headers: "readonly",
      HID: "readonly",
      HIDConnectionEvent: "readonly",
      HIDDevice: "readonly",
      HIDInputReportEvent: "readonly",
      Highlight: "readonly",
      HighlightRegistry: "readonly",
      history: "readonly",
      History: "readonly",
      HTMLAllCollection: "readonly",
      HTMLAnchorElement: "readonly",
      HTMLAreaElement: "readonly",
      HTMLAudioElement: "readonly",
      HTMLBaseElement: "readonly",
      HTMLBodyElement: "readonly",
      HTMLBRElement: "readonly",
      HTMLButtonElement: "readonly",
      HTMLCanvasElement: "readonly",
      HTMLCollection: "readonly",
      HTMLDataElement: "readonly",
      HTMLDataListElement: "readonly",
      HTMLDetailsElement: "readonly",
      HTMLDialogElement: "readonly",
      HTMLDirectoryElement: "readonly",
      HTMLDivElement: "readonly",
      HTMLDListElement: "readonly",
      HTMLDocument: "readonly",
      HTMLElement: "readonly",
      HTMLEmbedElement: "readonly",
      HTMLFencedFrameElement: "readonly",
      HTMLFieldSetElement: "readonly",
      HTMLFontElement: "readonly",
      HTMLFormControlsCollection: "readonly",
      HTMLFormElement: "readonly",
      HTMLFrameElement: "readonly",
      HTMLFrameSetElement: "readonly",
      HTMLHeadElement: "readonly",
      HTMLHeadingElement: "readonly",
      HTMLHRElement: "readonly",
      HTMLHtmlElement: "readonly",
      HTMLIFrameElement: "readonly",
      HTMLImageElement: "readonly",
      HTMLInputElement: "readonly",
      HTMLLabelElement: "readonly",
      HTMLLegendElement: "readonly",
      HTMLLIElement: "readonly",
      HTMLLinkElement: "readonly",
      HTMLMapElement: "readonly",
      HTMLMarqueeElement: "readonly",
      HTMLMediaElement: "readonly",
      HTMLMenuElement: "readonly",
      HTMLMetaElement: "readonly",
      HTMLMeterElement: "readonly",
      HTMLModElement: "readonly",
      HTMLObjectElement: "readonly",
      HTMLOListElement: "readonly",
      HTMLOptGroupElement: "readonly",
      HTMLOptionElement: "readonly",
      HTMLOptionsCollection: "readonly",
      HTMLOutputElement: "readonly",
      HTMLParagraphElement: "readonly",
      HTMLParamElement: "readonly",
      HTMLPictureElement: "readonly",
      HTMLPreElement: "readonly",
      HTMLProgressElement: "readonly",
      HTMLQuoteElement: "readonly",
      HTMLScriptElement: "readonly",
      HTMLSelectElement: "readonly",
      HTMLSlotElement: "readonly",
      HTMLSourceElement: "readonly",
      HTMLSpanElement: "readonly",
      HTMLStyleElement: "readonly",
      HTMLTableCaptionElement: "readonly",
      HTMLTableCellElement: "readonly",
      HTMLTableColElement: "readonly",
      HTMLTableElement: "readonly",
      HTMLTableRowElement: "readonly",
      HTMLTableSectionElement: "readonly",
      HTMLTemplateElement: "readonly",
      HTMLTextAreaElement: "readonly",
      HTMLTimeElement: "readonly",
      HTMLTitleElement: "readonly",
      HTMLTrackElement: "readonly",
      HTMLUListElement: "readonly",
      HTMLUnknownElement: "readonly",
      HTMLVideoElement: "readonly",
      IDBCursor: "readonly",
      IDBCursorWithValue: "readonly",
      IDBDatabase: "readonly",
      IDBFactory: "readonly",
      IDBIndex: "readonly",
      IDBKeyRange: "readonly",
      IDBObjectStore: "readonly",
      IDBOpenDBRequest: "readonly",
      IDBRequest: "readonly",
      IDBTransaction: "readonly",
      IDBVersionChangeEvent: "readonly",
      IdentityCredential: "readonly",
      IdentityCredentialError: "readonly",
      IdentityProvider: "readonly",
      IdleDeadline: "readonly",
      IdleDetector: "readonly",
      IIRFilterNode: "readonly",
      Image: "readonly",
      ImageBitmap: "readonly",
      ImageBitmapRenderingContext: "readonly",
      ImageCapture: "readonly",
      ImageData: "readonly",
      ImageDecoder: "readonly",
      ImageTrack: "readonly",
      ImageTrackList: "readonly",
      indexedDB: "readonly",
      Ink: "readonly",
      innerHeight: "readonly",
      innerWidth: "readonly",
      InputDeviceCapabilities: "readonly",
      InputDeviceInfo: "readonly",
      InputEvent: "readonly",
      IntersectionObserver: "readonly",
      IntersectionObserverEntry: "readonly",
      isSecureContext: "readonly",
      Keyboard: "readonly",
      KeyboardEvent: "readonly",
      KeyboardLayoutMap: "readonly",
      KeyframeEffect: "readonly",
      LargestContentfulPaint: "readonly",
      LaunchParams: "readonly",
      launchQueue: "readonly",
      LaunchQueue: "readonly",
      LayoutShift: "readonly",
      LayoutShiftAttribution: "readonly",
      length: "readonly",
      LinearAccelerationSensor: "readonly",
      localStorage: "readonly",
      location: "writable",
      Location: "readonly",
      locationbar: "readonly",
      Lock: "readonly",
      LockManager: "readonly",
      matchMedia: "readonly",
      MathMLElement: "readonly",
      MediaCapabilities: "readonly",
      MediaCapabilitiesInfo: "readonly",
      MediaDeviceInfo: "readonly",
      MediaDevices: "readonly",
      MediaElementAudioSourceNode: "readonly",
      MediaEncryptedEvent: "readonly",
      MediaError: "readonly",
      MediaKeyError: "readonly",
      MediaKeyMessageEvent: "readonly",
      MediaKeys: "readonly",
      MediaKeySession: "readonly",
      MediaKeyStatusMap: "readonly",
      MediaKeySystemAccess: "readonly",
      MediaList: "readonly",
      MediaMetadata: "readonly",
      MediaQueryList: "readonly",
      MediaQueryListEvent: "readonly",
      MediaRecorder: "readonly",
      MediaRecorderErrorEvent: "readonly",
      MediaSession: "readonly",
      MediaSource: "readonly",
      MediaSourceHandle: "readonly",
      MediaStream: "readonly",
      MediaStreamAudioDestinationNode: "readonly",
      MediaStreamAudioSourceNode: "readonly",
      MediaStreamEvent: "readonly",
      MediaStreamTrack: "readonly",
      MediaStreamTrackAudioSourceNode: "readonly",
      MediaStreamTrackAudioStats: "readonly",
      MediaStreamTrackEvent: "readonly",
      MediaStreamTrackGenerator: "readonly",
      MediaStreamTrackProcessor: "readonly",
      MediaStreamTrackVideoStats: "readonly",
      menubar: "readonly",
      MessageChannel: "readonly",
      MessageEvent: "readonly",
      MessagePort: "readonly",
      MIDIAccess: "readonly",
      MIDIConnectionEvent: "readonly",
      MIDIInput: "readonly",
      MIDIInputMap: "readonly",
      MIDIMessageEvent: "readonly",
      MIDIOutput: "readonly",
      MIDIOutputMap: "readonly",
      MIDIPort: "readonly",
      MimeType: "readonly",
      MimeTypeArray: "readonly",
      model: "readonly",
      ModelGenericSession: "readonly",
      ModelManager: "readonly",
      MouseEvent: "readonly",
      moveBy: "readonly",
      moveTo: "readonly",
      MutationEvent: "readonly",
      MutationObserver: "readonly",
      MutationRecord: "readonly",
      name: "readonly",
      NamedNodeMap: "readonly",
      NavigateEvent: "readonly",
      navigation: "readonly",
      Navigation: "readonly",
      NavigationActivation: "readonly",
      NavigationCurrentEntryChangeEvent: "readonly",
      NavigationDestination: "readonly",
      NavigationHistoryEntry: "readonly",
      NavigationPreloadManager: "readonly",
      NavigationTransition: "readonly",
      navigator: "readonly",
      Navigator: "readonly",
      NavigatorLogin: "readonly",
      NavigatorManagedData: "readonly",
      NavigatorUAData: "readonly",
      NetworkInformation: "readonly",
      Node: "readonly",
      NodeFilter: "readonly",
      NodeIterator: "readonly",
      NodeList: "readonly",
      Notification: "readonly",
      NotifyPaintEvent: "readonly",
      NotRestoredReasonDetails: "readonly",
      NotRestoredReasons: "readonly",
      OfflineAudioCompletionEvent: "readonly",
      OfflineAudioContext: "readonly",
      offscreenBuffering: "readonly",
      OffscreenCanvas: "readonly",
      OffscreenCanvasRenderingContext2D: "readonly",
      onabort: "writable",
      onafterprint: "writable",
      onanimationcancel: "writable",
      onanimationend: "writable",
      onanimationiteration: "writable",
      onanimationstart: "writable",
      onappinstalled: "writable",
      onauxclick: "writable",
      onbeforeinput: "writable",
      onbeforeinstallprompt: "writable",
      onbeforematch: "writable",
      onbeforeprint: "writable",
      onbeforetoggle: "writable",
      onbeforeunload: "writable",
      onbeforexrselect: "writable",
      onblur: "writable",
      oncancel: "writable",
      oncanplay: "writable",
      oncanplaythrough: "writable",
      onchange: "writable",
      onclick: "writable",
      onclose: "writable",
      oncontentvisibilityautostatechange: "writable",
      oncontextlost: "writable",
      oncontextmenu: "writable",
      oncontextrestored: "writable",
      oncopy: "writable",
      oncuechange: "writable",
      oncut: "writable",
      ondblclick: "writable",
      ondevicemotion: "writable",
      ondeviceorientation: "writable",
      ondeviceorientationabsolute: "writable",
      ondrag: "writable",
      ondragend: "writable",
      ondragenter: "writable",
      ondragleave: "writable",
      ondragover: "writable",
      ondragstart: "writable",
      ondrop: "writable",
      ondurationchange: "writable",
      onemptied: "writable",
      onended: "writable",
      onerror: "writable",
      onfocus: "writable",
      onformdata: "writable",
      ongamepadconnected: "writable",
      ongamepaddisconnected: "writable",
      ongotpointercapture: "writable",
      onhashchange: "writable",
      oninput: "writable",
      oninvalid: "writable",
      onkeydown: "writable",
      onkeypress: "writable",
      onkeyup: "writable",
      onlanguagechange: "writable",
      onload: "writable",
      onloadeddata: "writable",
      onloadedmetadata: "writable",
      onloadstart: "writable",
      onlostpointercapture: "writable",
      onmessage: "writable",
      onmessageerror: "writable",
      onmousedown: "writable",
      onmouseenter: "writable",
      onmouseleave: "writable",
      onmousemove: "writable",
      onmouseout: "writable",
      onmouseover: "writable",
      onmouseup: "writable",
      onmousewheel: "writable",
      onoffline: "writable",
      ononline: "writable",
      onpagehide: "writable",
      onpagereveal: "writable",
      onpageshow: "writable",
      onpageswap: "writable",
      onpaste: "writable",
      onpause: "writable",
      onplay: "writable",
      onplaying: "writable",
      onpointercancel: "writable",
      onpointerdown: "writable",
      onpointerenter: "writable",
      onpointerleave: "writable",
      onpointermove: "writable",
      onpointerout: "writable",
      onpointerover: "writable",
      onpointerrawupdate: "writable",
      onpointerup: "writable",
      onpopstate: "writable",
      onprogress: "writable",
      onratechange: "writable",
      onrejectionhandled: "writable",
      onreset: "writable",
      onresize: "writable",
      onscroll: "writable",
      onscrollend: "writable",
      onscrollsnapchange: "writable",
      onscrollsnapchanging: "writable",
      onsearch: "writable",
      onsecuritypolicyviolation: "writable",
      onseeked: "writable",
      onseeking: "writable",
      onselect: "writable",
      onselectionchange: "writable",
      onselectstart: "writable",
      onslotchange: "writable",
      onstalled: "writable",
      onstorage: "writable",
      onsubmit: "writable",
      onsuspend: "writable",
      ontimeupdate: "writable",
      ontoggle: "writable",
      ontransitioncancel: "writable",
      ontransitionend: "writable",
      ontransitionrun: "writable",
      ontransitionstart: "writable",
      onunhandledrejection: "writable",
      onunload: "writable",
      onvolumechange: "writable",
      onwaiting: "writable",
      onwheel: "writable",
      open: "readonly",
      opener: "readonly",
      Option: "readonly",
      OrientationSensor: "readonly",
      origin: "readonly",
      originAgentCluster: "readonly",
      OscillatorNode: "readonly",
      OTPCredential: "readonly",
      outerHeight: "readonly",
      outerWidth: "readonly",
      OverconstrainedError: "readonly",
      PageRevealEvent: "readonly",
      PageSwapEvent: "readonly",
      PageTransitionEvent: "readonly",
      pageXOffset: "readonly",
      pageYOffset: "readonly",
      PannerNode: "readonly",
      parent: "readonly",
      PasswordCredential: "readonly",
      Path2D: "readonly",
      PaymentAddress: "readonly",
      PaymentManager: "readonly",
      PaymentMethodChangeEvent: "readonly",
      PaymentRequest: "readonly",
      PaymentRequestUpdateEvent: "readonly",
      PaymentResponse: "readonly",
      performance: "readonly",
      Performance: "readonly",
      PerformanceElementTiming: "readonly",
      PerformanceEntry: "readonly",
      PerformanceEventTiming: "readonly",
      PerformanceLongAnimationFrameTiming: "readonly",
      PerformanceLongTaskTiming: "readonly",
      PerformanceMark: "readonly",
      PerformanceMeasure: "readonly",
      PerformanceNavigation: "readonly",
      PerformanceNavigationTiming: "readonly",
      PerformanceObserver: "readonly",
      PerformanceObserverEntryList: "readonly",
      PerformancePaintTiming: "readonly",
      PerformanceResourceTiming: "readonly",
      PerformanceScriptTiming: "readonly",
      PerformanceServerTiming: "readonly",
      PerformanceTiming: "readonly",
      PeriodicSyncManager: "readonly",
      PeriodicWave: "readonly",
      Permissions: "readonly",
      PermissionStatus: "readonly",
      PERSISTENT: "readonly",
      personalbar: "readonly",
      PictureInPictureEvent: "readonly",
      PictureInPictureWindow: "readonly",
      Plugin: "readonly",
      PluginArray: "readonly",
      PointerEvent: "readonly",
      PopStateEvent: "readonly",
      postMessage: "readonly",
      Presentation: "readonly",
      PresentationAvailability: "readonly",
      PresentationConnection: "readonly",
      PresentationConnectionAvailableEvent: "readonly",
      PresentationConnectionCloseEvent: "readonly",
      PresentationConnectionList: "readonly",
      PresentationReceiver: "readonly",
      PresentationRequest: "readonly",
      PressureObserver: "readonly",
      PressureRecord: "readonly",
      print: "readonly",
      ProcessingInstruction: "readonly",
      Profiler: "readonly",
      ProgressEvent: "readonly",
      PromiseRejectionEvent: "readonly",
      prompt: "readonly",
      ProtectedAudience: "readonly",
      PublicKeyCredential: "readonly",
      PushManager: "readonly",
      PushSubscription: "readonly",
      PushSubscriptionOptions: "readonly",
      queryLocalFonts: "readonly",
      queueMicrotask: "readonly",
      RadioNodeList: "readonly",
      Range: "readonly",
      ReadableByteStreamController: "readonly",
      ReadableStream: "readonly",
      ReadableStreamBYOBReader: "readonly",
      ReadableStreamBYOBRequest: "readonly",
      ReadableStreamDefaultController: "readonly",
      ReadableStreamDefaultReader: "readonly",
      registerProcessor: "readonly",
      RelativeOrientationSensor: "readonly",
      RemotePlayback: "readonly",
      removeEventListener: "readonly",
      reportError: "readonly",
      ReportingObserver: "readonly",
      Request: "readonly",
      requestAnimationFrame: "readonly",
      requestIdleCallback: "readonly",
      resizeBy: "readonly",
      ResizeObserver: "readonly",
      ResizeObserverEntry: "readonly",
      ResizeObserverSize: "readonly",
      resizeTo: "readonly",
      Response: "readonly",
      RTCCertificate: "readonly",
      RTCDataChannel: "readonly",
      RTCDataChannelEvent: "readonly",
      RTCDtlsTransport: "readonly",
      RTCDTMFSender: "readonly",
      RTCDTMFToneChangeEvent: "readonly",
      RTCEncodedAudioFrame: "readonly",
      RTCEncodedVideoFrame: "readonly",
      RTCError: "readonly",
      RTCErrorEvent: "readonly",
      RTCIceCandidate: "readonly",
      RTCIceTransport: "readonly",
      RTCPeerConnection: "readonly",
      RTCPeerConnectionIceErrorEvent: "readonly",
      RTCPeerConnectionIceEvent: "readonly",
      RTCRtpReceiver: "readonly",
      RTCRtpScriptTransform: "readonly",
      RTCRtpSender: "readonly",
      RTCRtpTransceiver: "readonly",
      RTCSctpTransport: "readonly",
      RTCSessionDescription: "readonly",
      RTCStatsReport: "readonly",
      RTCTrackEvent: "readonly",
      sampleRate: "readonly",
      scheduler: "readonly",
      Scheduler: "readonly",
      Scheduling: "readonly",
      screen: "readonly",
      Screen: "readonly",
      ScreenDetailed: "readonly",
      ScreenDetails: "readonly",
      screenLeft: "readonly",
      ScreenOrientation: "readonly",
      screenTop: "readonly",
      screenX: "readonly",
      screenY: "readonly",
      ScriptProcessorNode: "readonly",
      scroll: "readonly",
      scrollbars: "readonly",
      scrollBy: "readonly",
      ScrollTimeline: "readonly",
      scrollTo: "readonly",
      scrollX: "readonly",
      scrollY: "readonly",
      SecurityPolicyViolationEvent: "readonly",
      Selection: "readonly",
      self: "readonly",
      Sensor: "readonly",
      SensorErrorEvent: "readonly",
      Serial: "readonly",
      SerialPort: "readonly",
      ServiceWorker: "readonly",
      ServiceWorkerContainer: "readonly",
      ServiceWorkerRegistration: "readonly",
      sessionStorage: "readonly",
      setInterval: "readonly",
      setTimeout: "readonly",
      ShadowRoot: "readonly",
      sharedStorage: "readonly",
      SharedStorage: "readonly",
      SharedStorageWorklet: "readonly",
      SharedWorker: "readonly",
      showDirectoryPicker: "readonly",
      showOpenFilePicker: "readonly",
      showSaveFilePicker: "readonly",
      SnapEvent: "readonly",
      SourceBuffer: "readonly",
      SourceBufferList: "readonly",
      speechSynthesis: "readonly",
      SpeechSynthesis: "readonly",
      SpeechSynthesisErrorEvent: "readonly",
      SpeechSynthesisEvent: "readonly",
      SpeechSynthesisUtterance: "readonly",
      SpeechSynthesisVoice: "readonly",
      StaticRange: "readonly",
      status: "readonly",
      statusbar: "readonly",
      StereoPannerNode: "readonly",
      stop: "readonly",
      Storage: "readonly",
      StorageBucket: "readonly",
      StorageBucketManager: "readonly",
      StorageEvent: "readonly",
      StorageManager: "readonly",
      structuredClone: "readonly",
      styleMedia: "readonly",
      StylePropertyMap: "readonly",
      StylePropertyMapReadOnly: "readonly",
      StyleSheet: "readonly",
      StyleSheetList: "readonly",
      SubmitEvent: "readonly",
      SubtleCrypto: "readonly",
      SVGAElement: "readonly",
      SVGAngle: "readonly",
      SVGAnimatedAngle: "readonly",
      SVGAnimatedBoolean: "readonly",
      SVGAnimatedEnumeration: "readonly",
      SVGAnimatedInteger: "readonly",
      SVGAnimatedLength: "readonly",
      SVGAnimatedLengthList: "readonly",
      SVGAnimatedNumber: "readonly",
      SVGAnimatedNumberList: "readonly",
      SVGAnimatedPreserveAspectRatio: "readonly",
      SVGAnimatedRect: "readonly",
      SVGAnimatedString: "readonly",
      SVGAnimatedTransformList: "readonly",
      SVGAnimateElement: "readonly",
      SVGAnimateMotionElement: "readonly",
      SVGAnimateTransformElement: "readonly",
      SVGAnimationElement: "readonly",
      SVGCircleElement: "readonly",
      SVGClipPathElement: "readonly",
      SVGComponentTransferFunctionElement: "readonly",
      SVGDefsElement: "readonly",
      SVGDescElement: "readonly",
      SVGElement: "readonly",
      SVGEllipseElement: "readonly",
      SVGFEBlendElement: "readonly",
      SVGFEColorMatrixElement: "readonly",
      SVGFEComponentTransferElement: "readonly",
      SVGFECompositeElement: "readonly",
      SVGFEConvolveMatrixElement: "readonly",
      SVGFEDiffuseLightingElement: "readonly",
      SVGFEDisplacementMapElement: "readonly",
      SVGFEDistantLightElement: "readonly",
      SVGFEDropShadowElement: "readonly",
      SVGFEFloodElement: "readonly",
      SVGFEFuncAElement: "readonly",
      SVGFEFuncBElement: "readonly",
      SVGFEFuncGElement: "readonly",
      SVGFEFuncRElement: "readonly",
      SVGFEGaussianBlurElement: "readonly",
      SVGFEImageElement: "readonly",
      SVGFEMergeElement: "readonly",
      SVGFEMergeNodeElement: "readonly",
      SVGFEMorphologyElement: "readonly",
      SVGFEOffsetElement: "readonly",
      SVGFEPointLightElement: "readonly",
      SVGFESpecularLightingElement: "readonly",
      SVGFESpotLightElement: "readonly",
      SVGFETileElement: "readonly",
      SVGFETurbulenceElement: "readonly",
      SVGFilterElement: "readonly",
      SVGForeignObjectElement: "readonly",
      SVGGElement: "readonly",
      SVGGeometryElement: "readonly",
      SVGGradientElement: "readonly",
      SVGGraphicsElement: "readonly",
      SVGImageElement: "readonly",
      SVGLength: "readonly",
      SVGLengthList: "readonly",
      SVGLinearGradientElement: "readonly",
      SVGLineElement: "readonly",
      SVGMarkerElement: "readonly",
      SVGMaskElement: "readonly",
      SVGMatrix: "readonly",
      SVGMetadataElement: "readonly",
      SVGMPathElement: "readonly",
      SVGNumber: "readonly",
      SVGNumberList: "readonly",
      SVGPathElement: "readonly",
      SVGPatternElement: "readonly",
      SVGPoint: "readonly",
      SVGPointList: "readonly",
      SVGPolygonElement: "readonly",
      SVGPolylineElement: "readonly",
      SVGPreserveAspectRatio: "readonly",
      SVGRadialGradientElement: "readonly",
      SVGRect: "readonly",
      SVGRectElement: "readonly",
      SVGScriptElement: "readonly",
      SVGSetElement: "readonly",
      SVGStopElement: "readonly",
      SVGStringList: "readonly",
      SVGStyleElement: "readonly",
      SVGSVGElement: "readonly",
      SVGSwitchElement: "readonly",
      SVGSymbolElement: "readonly",
      SVGTextContentElement: "readonly",
      SVGTextElement: "readonly",
      SVGTextPathElement: "readonly",
      SVGTextPositioningElement: "readonly",
      SVGTitleElement: "readonly",
      SVGTransform: "readonly",
      SVGTransformList: "readonly",
      SVGTSpanElement: "readonly",
      SVGUnitTypes: "readonly",
      SVGUseElement: "readonly",
      SVGViewElement: "readonly",
      SyncManager: "readonly",
      TaskAttributionTiming: "readonly",
      TaskController: "readonly",
      TaskPriorityChangeEvent: "readonly",
      TaskSignal: "readonly",
      TEMPORARY: "readonly",
      Text: "readonly",
      TextDecoder: "readonly",
      TextDecoderStream: "readonly",
      TextEncoder: "readonly",
      TextEncoderStream: "readonly",
      TextEvent: "readonly",
      TextFormat: "readonly",
      TextFormatUpdateEvent: "readonly",
      TextMetrics: "readonly",
      TextTrack: "readonly",
      TextTrackCue: "readonly",
      TextTrackCueList: "readonly",
      TextTrackList: "readonly",
      TextUpdateEvent: "readonly",
      TimeEvent: "readonly",
      TimeRanges: "readonly",
      ToggleEvent: "readonly",
      toolbar: "readonly",
      top: "readonly",
      Touch: "readonly",
      TouchEvent: "readonly",
      TouchList: "readonly",
      TrackEvent: "readonly",
      TransformStream: "readonly",
      TransformStreamDefaultController: "readonly",
      TransitionEvent: "readonly",
      TreeWalker: "readonly",
      TrustedHTML: "readonly",
      TrustedScript: "readonly",
      TrustedScriptURL: "readonly",
      TrustedTypePolicy: "readonly",
      TrustedTypePolicyFactory: "readonly",
      trustedTypes: "readonly",
      UIEvent: "readonly",
      URL: "readonly",
      URLPattern: "readonly",
      URLSearchParams: "readonly",
      USB: "readonly",
      USBAlternateInterface: "readonly",
      USBConfiguration: "readonly",
      USBConnectionEvent: "readonly",
      USBDevice: "readonly",
      USBEndpoint: "readonly",
      USBInterface: "readonly",
      USBInTransferResult: "readonly",
      USBIsochronousInTransferPacket: "readonly",
      USBIsochronousInTransferResult: "readonly",
      USBIsochronousOutTransferPacket: "readonly",
      USBIsochronousOutTransferResult: "readonly",
      USBOutTransferResult: "readonly",
      UserActivation: "readonly",
      ValidityState: "readonly",
      VideoColorSpace: "readonly",
      VideoDecoder: "readonly",
      VideoEncoder: "readonly",
      VideoFrame: "readonly",
      VideoPlaybackQuality: "readonly",
      ViewTimeline: "readonly",
      ViewTransition: "readonly",
      ViewTransitionTypeSet: "readonly",
      VirtualKeyboard: "readonly",
      VirtualKeyboardGeometryChangeEvent: "readonly",
      VisibilityStateEntry: "readonly",
      visualViewport: "readonly",
      VisualViewport: "readonly",
      VTTCue: "readonly",
      VTTRegion: "readonly",
      WakeLock: "readonly",
      WakeLockSentinel: "readonly",
      WaveShaperNode: "readonly",
      WebAssembly: "readonly",
      WebGL2RenderingContext: "readonly",
      WebGLActiveInfo: "readonly",
      WebGLBuffer: "readonly",
      WebGLContextEvent: "readonly",
      WebGLFramebuffer: "readonly",
      WebGLObject: "readonly",
      WebGLProgram: "readonly",
      WebGLQuery: "readonly",
      WebGLRenderbuffer: "readonly",
      WebGLRenderingContext: "readonly",
      WebGLSampler: "readonly",
      WebGLShader: "readonly",
      WebGLShaderPrecisionFormat: "readonly",
      WebGLSync: "readonly",
      WebGLTexture: "readonly",
      WebGLTransformFeedback: "readonly",
      WebGLUniformLocation: "readonly",
      WebGLVertexArrayObject: "readonly",
      WebSocket: "readonly",
      WebSocketError: "readonly",
      WebSocketStream: "readonly",
      WebTransport: "readonly",
      WebTransportBidirectionalStream: "readonly",
      WebTransportDatagramDuplexStream: "readonly",
      WebTransportError: "readonly",
      WebTransportReceiveStream: "readonly",
      WebTransportSendStream: "readonly",
      WGSLLanguageFeatures: "readonly",
      WheelEvent: "readonly",
      window: "readonly",
      Window: "readonly",
      WindowControlsOverlay: "readonly",
      WindowControlsOverlayGeometryChangeEvent: "readonly",
      Worker: "readonly",
      Worklet: "readonly",
      WorkletGlobalScope: "readonly",
      WritableStream: "readonly",
      WritableStreamDefaultController: "readonly",
      WritableStreamDefaultWriter: "readonly",
      XMLDocument: "readonly",
      XMLHttpRequest: "readonly",
      XMLHttpRequestEventTarget: "readonly",
      XMLHttpRequestUpload: "readonly",
      XMLSerializer: "readonly",
      XPathEvaluator: "readonly",
      XPathExpression: "readonly",
      XPathResult: "readonly",
      XRAnchor: "readonly",
      XRAnchorSet: "readonly",
      XRBoundedReferenceSpace: "readonly",
      XRCamera: "readonly",
      XRCPUDepthInformation: "readonly",
      XRDepthInformation: "readonly",
      XRDOMOverlayState: "readonly",
      XRFrame: "readonly",
      XRHand: "readonly",
      XRHitTestResult: "readonly",
      XRHitTestSource: "readonly",
      XRInputSource: "readonly",
      XRInputSourceArray: "readonly",
      XRInputSourceEvent: "readonly",
      XRInputSourcesChangeEvent: "readonly",
      XRJointPose: "readonly",
      XRJointSpace: "readonly",
      XRLayer: "readonly",
      XRLightEstimate: "readonly",
      XRLightProbe: "readonly",
      XRPose: "readonly",
      XRRay: "readonly",
      XRReferenceSpace: "readonly",
      XRReferenceSpaceEvent: "readonly",
      XRRenderState: "readonly",
      XRRigidTransform: "readonly",
      XRSession: "readonly",
      XRSessionEvent: "readonly",
      XRSpace: "readonly",
      XRSystem: "readonly",
      XRTransientInputHitTestResult: "readonly",
      XRTransientInputHitTestSource: "readonly",
      XRView: "readonly",
      XRViewerPose: "readonly",
      XRViewport: "readonly",
      XRWebGLBinding: "readonly",
      XRWebGLDepthInformation: "readonly",
      XRWebGLLayer: "readonly",
      XSLTProcessor: "readonly",
      __dirname: "readonly",
      __filename: "readonly",
      Buffer: "readonly",
      clearImmediate: "readonly",
      process: "readonly",
      setImmediate: "readonly",
      computed: "readonly",
      defineEmits: "readonly",
      defineExpose: "readonly",
      defineProps: "readonly",
      onMounted: "readonly",
      onUnmounted: "readonly",
      reactive: "readonly",
      ref: "readonly",
      shallowReactive: "readonly",
      shallowRef: "readonly",
      toRef: "readonly",
      toRefs: "readonly",
      watch: "readonly",
      watchEffect: "readonly",
    },
    ignorePatterns: [
      "coverage",
      "build",
      "**/.DS_Store",
      "**/*.pem",
      "**/npm-debug.log*",
      "**/yarn-debug.log*",
      "**/yarn-error.log*",
      "**/.pnpm-debug.log*",
      "**/.env*.local",
      "**/.vercel",
      "**/*.tsbuildinfo",
      "**/next-env.d.ts",
      "**/report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json",
      "**/pids",
      "**/*.pid",
      "**/*.seed",
      "**/*.pid.lock",
      "**/lib-cov",
      "**/coverage",
      "**/*.lcov",
      "**/.nyc_output",
      "**/.lock-wscript",
      "build/Release",
      "**/node_modules/",
      "**/jspm_packages/",
      "**/.npm",
      "**/.eslintcache",
      "**/.stylelintcache",
      "**/.rpt2_cache/",
      "**/.rts2_cache_cjs/",
      "**/.rts2_cache_es/",
      "**/.rts2_cache_umd/",
      "**/.node_repl_history",
      "**/*.tgz",
      "**/.yarn-integrity",
      "**/.env",
      "**/.env.development.local",
      "**/.env.test.local",
      "**/.env.production.local",
      "**/.env.local",
      "**/.cache",
      "**/.parcel-cache",
      "**/.nuxt",
      "**/dist",
      "**/.vscode-test",
      ".yarn/cache",
      ".yarn/unplugged",
      ".yarn/build-state.yml",
      ".yarn/install-state.gz",
      "**/.pnp.*",
      "**/.nuxt-*",
      "**/.output",
      "**/.gen",
      "**/node_modules",
      "docs/.vitepress/dist",
      "docs/.vitepress/cache",
      "**/.agents/",
      "**/package-lock.json",
      "**/yarn.lock",
      "**/pnpm-lock.yaml",
      "**/bun.lockb",
      "**/output",
      "**/temp",
      "**/.temp",
      "**/tmp",
      "**/.tmp",
      "**/.history",
      "**/.vitepress/cache",
      "**/.next",
      "**/.svelte-kit",
      "**/.changeset",
      "**/.idea",
      "**/.vite-inspect",
      "**/.yarn",
      "**/vite.config.*.timestamp-*",
      "**/CHANGELOG*.md",
      "**/*.min.*",
      "**/LICENSE*",
      "**/__snapshots__",
      "**/auto-import?(s).d.ts",
      "**/components.d.ts",
      "goal.md",
      ".agents",
      ".agents/**",
    ],
    rules: {
      "accessor-pairs": [
        "error",
        {
          enforceForClassMembers: true,
          setWithoutGet: true,
        },
      ],
      "array-callback-return": "error",
      "block-scoped-var": "error",
      "constructor-super": "error",
      "default-case-last": "error",
      eqeqeq: ["error", "smart"],
      "new-cap": [
        "error",
        {
          capIsNew: false,
          newIsCap: true,
          properties: true,
        },
      ],
      "no-alert": "error",
      "no-array-constructor": "error",
      "no-async-promise-executor": "error",
      "no-caller": "error",
      "no-case-declarations": "error",
      "no-class-assign": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": ["error", "always"],
      "no-console": [
        "error",
        {
          allow: ["warn", "error"],
        },
      ],
      "no-const-assign": "error",
      "no-control-regex": "error",
      "no-debugger": "error",
      "no-delete-var": "error",
      "no-dupe-class-members": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty": [
        "error",
        {
          allowEmptyCatch: true,
        },
      ],
      "no-empty-character-class": "error",
      "no-empty-pattern": "error",
      "no-eval": "error",
      "no-ex-assign": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-extra-boolean-cast": "error",
      "no-fallthrough": "error",
      "no-func-assign": "error",
      "no-global-assign": "error",
      "no-implied-eval": "error",
      "no-import-assign": "error",
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-iterator": "error",
      "no-labels": [
        "error",
        {
          allowLoop: false,
          allowSwitch: false,
        },
      ],
      "no-lone-blocks": "error",
      "no-loss-of-precision": "error",
      "no-misleading-character-class": "error",
      "no-multi-str": "error",
      "no-new": "error",
      "no-new-func": "error",
      "no-new-native-nonconstructor": "error",
      "no-new-wrappers": "error",
      "no-obj-calls": "error",
      "no-proto": "error",
      "no-prototype-builtins": "error",
      "no-redeclare": [
        "error",
        {
          builtinGlobals: false,
        },
      ],
      "no-regex-spaces": "error",
      "no-restricted-globals": [
        "error",
        {
          message: "Use `globalThis` instead.",
          name: "global",
        },
        {
          message: "Use `globalThis` instead.",
          name: "self",
        },
      ],
      "no-restricted-properties": [
        "error",
        {
          message: "Use `Object.getPrototypeOf` or `Object.setPrototypeOf` instead.",
          property: "__proto__",
        },
        {
          message: "Use `Object.defineProperty` instead.",
          property: "__defineGetter__",
        },
        {
          message: "Use `Object.defineProperty` instead.",
          property: "__defineSetter__",
        },
        {
          message: "Use `Object.getOwnPropertyDescriptor` instead.",
          property: "__lookupGetter__",
        },
        {
          message: "Use `Object.getOwnPropertyDescriptor` instead.",
          property: "__lookupSetter__",
        },
      ],
      "no-self-assign": [
        "error",
        {
          props: true,
        },
      ],
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-shadow-restricted-names": "error",
      "no-sparse-arrays": "error",
      "no-template-curly-in-string": "error",
      "no-this-before-super": "error",
      "no-throw-literal": "error",
      "no-undef": "error",
      "no-unexpected-multiline": "error",
      "no-unmodified-loop-condition": "error",
      "no-unneeded-ternary": [
        "error",
        {
          defaultAssignment: false,
        },
      ],
      "no-unreachable": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "no-unused-expressions": [
        "error",
        {
          allowShortCircuit: true,
          allowTaggedTemplates: true,
          allowTernary: true,
        },
      ],
      "no-unused-vars": [
        "error",
        {
          args: "none",
          caughtErrors: "none",
          ignoreRestSiblings: true,
          vars: "all",
        },
      ],
      "no-use-before-define": [
        "error",
        {
          classes: false,
          functions: false,
          variables: true,
        },
      ],
      "no-useless-backreference": "error",
      "no-useless-call": "error",
      "no-useless-catch": "error",
      "no-useless-computed-key": "error",
      "no-useless-constructor": "error",
      "no-useless-rename": "error",
      "no-useless-return": "error",
      "no-var": "error",
      "no-with": "error",
      "object-shorthand": [
        "error",
        "always",
        {
          avoidQuotes: true,
          ignoreConstructors: false,
        },
      ],
      "prefer-arrow-callback": [
        "error",
        {
          allowNamedFunctions: false,
          allowUnboundThis: true,
        },
      ],
      "prefer-const": [
        "warn",
        {
          destructuring: "all",
          ignoreReadBeforeAssign: true,
        },
      ],
      "prefer-exponentiation-operator": "error",
      "prefer-promise-reject-errors": "error",
      "prefer-regex-literals": [
        "error",
        {
          disallowRedundantWrapping: true,
        },
      ],
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "prefer-template": "error",
      "symbol-description": "error",
      "unicode-bom": ["error", "never"],
      "use-isnan": [
        "error",
        {
          enforceForIndexOf: true,
          enforceForSwitchCase: true,
        },
      ],
      "valid-typeof": [
        "error",
        {
          requireStringLiterals: true,
        },
      ],
      "vars-on-top": "error",
      yoda: ["error", "never"],
      "node/handle-callback-err": ["error", "^(err|error)$"],
      "node/no-exports-assign": "error",
      "node/no-new-require": "error",
      "node/no-path-concat": "error",
      "jsdoc/check-access": "warn",
      "jsdoc/empty-tags": "warn",
      "jsdoc/require-param-name": "warn",
      "jsdoc/require-returns-description": "warn",
      "import/first": "error",
      "import/no-duplicates": "error",
      "import/no-mutable-exports": "error",
      "import/no-named-default": "error",
      "import/no-self-import": "error",
      "import/no-webpack-loader-syntax": "error",
      "import/newline-after-import": [
        "error",
        {
          count: 1,
        },
      ],
      "unicorn/consistent-empty-array-spread": "error",
      "unicorn/error-message": "error",
      "unicorn/escape-case": "error",
      "unicorn/new-for-builtins": "error",
      "unicorn/no-instanceof-array": "error",
      "unicorn/no-new-array": "error",
      "unicorn/no-new-buffer": "error",
      "unicorn/number-literal-case": "error",
      "unicorn/prefer-dom-node-text-content": "error",
      "unicorn/prefer-includes": "error",
      "unicorn/prefer-node-protocol": "error",
      "unicorn/prefer-number-properties": "error",
      "unicorn/prefer-string-starts-ends-with": "error",
      "unicorn/prefer-type-error": "error",
      "unicorn/throw-new-error": "error",
      "typescript/dot-notation": [
        "error",
        {
          allowKeywords: true,
        },
      ],
      "vite-plus/prefer-vite-plus-imports": "error",
    },
    overrides: [
      {
        files: ["**/*.?([cm])ts", "**/*.?([cm])tsx", "**/*.vue"],
        rules: {
          "constructor-super": "off",
          "getter-return": "off",
          "no-class-assign": "off",
          "no-const-assign": "off",
          "no-dupe-keys": "off",
          "no-func-assign": "off",
          "no-import-assign": "off",
          "no-new-native-nonconstructor": "off",
          "no-obj-calls": "off",
          "no-redeclare": [
            "error",
            {
              builtinGlobals: false,
            },
          ],
          "no-setter-return": "off",
          "no-this-before-super": "off",
          "no-undef": "off",
          "no-unreachable": "off",
          "no-unsafe-negation": "off",
          "no-with": "off",
          "prefer-const": "error",
          "no-unused-expressions": [
            "error",
            {
              allowShortCircuit: true,
              allowTaggedTemplates: true,
              allowTernary: true,
            },
          ],
          "no-unused-vars": "off",
          "no-useless-constructor": "off",
          "no-use-before-define": [
            "error",
            {
              classes: false,
              functions: false,
              variables: true,
            },
          ],
          "typescript/ban-ts-comment": [
            "error",
            {
              "ts-expect-error": "allow-with-description",
            },
          ],
          "typescript/no-duplicate-enum-values": "error",
          "typescript/no-dynamic-delete": "off",
          "typescript/no-empty-object-type": [
            "error",
            {
              allowInterfaces: "always",
            },
          ],
          "typescript/no-explicit-any": "off",
          "typescript/no-extra-non-null-assertion": "error",
          "typescript/no-extraneous-class": "off",
          "typescript/no-invalid-void-type": "off",
          "typescript/no-misused-new": "error",
          "typescript/no-namespace": "error",
          "typescript/no-non-null-asserted-nullish-coalescing": "error",
          "typescript/no-non-null-asserted-optional-chain": "error",
          "typescript/no-non-null-assertion": "off",
          "typescript/no-require-imports": "error",
          "typescript/no-this-alias": "error",
          "typescript/no-unnecessary-type-constraint": "error",
          "typescript/no-unsafe-declaration-merging": "error",
          "typescript/no-unsafe-function-type": "error",
          "typescript/no-wrapper-object-types": "error",
          "typescript/prefer-as-const": "error",
          "typescript/prefer-literal-enum-member": "error",
          "typescript/prefer-namespace-keyword": "error",
          "typescript/triple-slash-reference": "off",
          "typescript/unified-signatures": "off",
          "typescript/consistent-type-definitions": ["error", "interface"],
          "typescript/consistent-type-imports": [
            "error",
            {
              disallowTypeAnnotations: false,
              prefer: "type-imports",
            },
          ],
          "typescript/no-import-type-side-effects": "error",
        },
      },
      {
        files: [
          "**/__tests__/**/*.?([cm])[jt]s?(x)",
          "**/*.spec.?([cm])[jt]s?(x)",
          "**/*.test.?([cm])[jt]s?(x)",
          "**/*.bench.?([cm])[jt]s?(x)",
          "**/*.benchmark.?([cm])[jt]s?(x)",
        ],
        rules: {
          "vitest/consistent-test-it": [
            "error",
            {
              fn: "it",
              withinDescribe: "it",
            },
          ],
          "vitest/no-identical-title": "error",
          "vitest/no-import-node-test": "error",
          "vitest/prefer-hooks-in-order": "error",
          "vitest/prefer-lowercase-title": "error",
          "no-unused-expressions": "off",
          "typescript/explicit-function-return-type": "off",
        },
        jsPlugins: [],
        plugins: ["vitest"],
      },
      {
        files: ["**/*.vue"],
        rules: {
          "vue/no-arrow-functions-in-watch": "error",
          "vue/no-computed-properties-in-data": "error",
          "vue/no-deprecated-data-object-declaration": "error",
          "vue/no-deprecated-destroyed-lifecycle": "error",
          "vue/no-deprecated-events-api": "error",
          "vue/no-deprecated-props-default-this": "error",
          "vue/no-deprecated-vue-config-keycodes": "error",
          "vue/no-export-in-script-setup": "error",
          "vue/no-expose-after-await": "error",
          "vue/no-lifecycle-after-await": "error",
          "vue/no-shared-component-data": "error",
          "vue/no-watch-after-await": "error",
          "vue/prefer-import-from-vue": "error",
          "vue/require-render-return": "error",
          "vue/require-slots-as-functions": "error",
          "vue/return-in-computed-property": "error",
          "vue/return-in-emits-validator": "error",
          "vue/valid-define-emits": "error",
          "vue/valid-define-props": "error",
          "vue/valid-next-tick": "error",
          "vue/no-multiple-slot-args": "warn",
          "typescript/explicit-function-return-type": "off",
        },
        jsPlugins: [],
        plugins: ["vue"],
      },
      {
        files: ["**/*.json", "**/*.json5", "**/*.jsonc"],
        rules: {},
        jsPlugins: [],
      },
      {
        files: ["**/package.json"],
        rules: {},
        jsPlugins: [],
      },
      {
        files: ["**/tsconfig.json", "**/tsconfig.*.json"],
        rules: {},
        jsPlugins: [],
      },
      {
        files: ["**/*.y?(a)ml"],
        rules: {},
        jsPlugins: [],
      },
      {
        files: ["**/*.toml"],
        rules: {},
        jsPlugins: [],
      },
      {
        files: ["**/*.md/**/*.?([cm])[jt]s?(x)", "**/*.md/**/*.vue"],
        rules: {
          "import/newline-after-import": "off",
          "no-alert": "off",
          "no-console": "off",
          "no-labels": "off",
          "no-lone-blocks": "off",
          "no-undef": "off",
          "no-unused-expressions": "off",
          "no-unused-labels": "off",
          "no-unused-vars": "off",
          "unicode-bom": "off",
          "no-redeclare": "off",
          "no-use-before-define": "off",
          "typescript/consistent-type-imports": "off",
          "typescript/explicit-function-return-type": "off",
          "typescript/no-namespace": "off",
          "typescript/no-require-imports": "off",
        },
        jsPlugins: [],
      },
      {
        files: ["**/*.css", "**/*.{p,post}css"],
        rules: {
          "format/prettier": [
            "error",
            {
              endOfLine: "auto",
              printWidth: 120,
              semi: false,
              singleQuote: true,
              tabWidth: 2,
              trailingComma: "all",
              useTabs: false,
              parser: "css",
              plugins: [],
            },
          ],
        },
        jsPlugins: ["eslint-plugin-format"],
      },
      {
        files: ["**/*.scss"],
        rules: {
          "format/prettier": [
            "error",
            {
              endOfLine: "auto",
              printWidth: 120,
              semi: false,
              singleQuote: true,
              tabWidth: 2,
              trailingComma: "all",
              useTabs: false,
              parser: "scss",
              plugins: [],
            },
          ],
        },
        jsPlugins: ["eslint-plugin-format"],
      },
      {
        files: ["**/*.less"],
        rules: {
          "format/prettier": [
            "error",
            {
              endOfLine: "auto",
              printWidth: 120,
              semi: false,
              singleQuote: true,
              tabWidth: 2,
              trailingComma: "all",
              useTabs: false,
              parser: "less",
              plugins: [],
            },
          ],
        },
        jsPlugins: ["eslint-plugin-format"],
      },
      {
        files: ["**/*.htm?(l)"],
        rules: {
          "format/prettier": [
            "error",
            {
              endOfLine: "auto",
              printWidth: 120,
              semi: false,
              singleQuote: true,
              tabWidth: 2,
              trailingComma: "all",
              useTabs: false,
              parser: "html",
              plugins: [],
            },
          ],
        },
        jsPlugins: ["eslint-plugin-format"],
      },
      {
        files: ["**/*.md"],
        rules: {
          "format/prettier": [
            "error",
            {
              endOfLine: "auto",
              printWidth: 120,
              semi: false,
              singleQuote: true,
              tabWidth: 2,
              trailingComma: "all",
              useTabs: false,
              embeddedLanguageFormatting: "off",
              parser: "markdown",
              plugins: [],
            },
          ],
        },
        jsPlugins: ["eslint-plugin-format"],
      },
      {
        files: ["**/*.{g,graph}ql"],
        rules: {
          "format/prettier": [
            "error",
            {
              endOfLine: "auto",
              printWidth: 120,
              semi: false,
              singleQuote: true,
              tabWidth: 2,
              trailingComma: "all",
              useTabs: false,
              parser: "graphql",
              plugins: [],
            },
          ],
        },
        jsPlugins: ["eslint-plugin-format"],
      },
      {
        files: ["scripts/**/*.ts", "scripts/**/*.mts", "scripts/**/*.cts"],
        rules: {
          "no-console": "off",
          "typescript/explicit-function-return-type": "off",
        },
        jsPlugins: [],
      },
      {
        files: ["docs/.vitepress/**/*.mts", "docs/.vitepress/**/*.ts", "docs/vite.config.ts"],
        rules: {
          "vite-plus/prefer-vite-plus-imports": "off",
        },
        jsPlugins: [],
      },
      {
        files: ["**/cli/**/*.?([cm])[jt]s?(x)", "**/cli.?([cm])[jt]s?(x)"],
        rules: {
          "no-console": "off",
        },
        jsPlugins: [],
      },
      {
        files: ["**/bin/**/*", "**/bin.?([cm])[jt]s?(x)"],
        rules: {},
        jsPlugins: [],
      },
      {
        files: ["**/*.d.?([cm])ts"],
        rules: {
          "import/no-duplicates": "off",
        },
        jsPlugins: [],
      },
      {
        files: ["**/*.js", "**/*.cjs"],
        rules: {
          "typescript/no-require-imports": "off",
        },
      },
      {
        files: ["**/*.config.?([cm])[jt]s?(x)", "**/*.config.*.?([cm])[jt]s?(x)"],
        rules: {
          "no-console": "off",
          "typescript/explicit-function-return-type": "off",
        },
        jsPlugins: [],
      },
    ],
  },
});
