name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - name: Set node
        uses: actions/setup-node@v5
        with:
          node-version-file: .node-version

      - name: Install
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint

      - name: Typecheck
        run: bun run typecheck

      - name: Check repository normalization
        run: bun run normalize:repository:check

      - name: Build
        run: bun run build

      - name: Test
        run: bun run test

      - name: Create GitHub release
        run: bunx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
